# Generated by Django 2.0.1 on 2019-09-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名')),
                ('category_url', models.CharField(max_length=200, verbose_name='分类图片')),
                ('father_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Funy.CategoryModel', verbose_name='父分类名')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='YgeatModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('eat_content', models.CharField(max_length=50, verbose_name='描述')),
                ('eat_time', models.CharField(max_length=20, verbose_name='时间')),
                ('hot', models.IntegerField(verbose_name='热度')),
            ],
            options={
                'verbose_name': '吃喝玩乐',
                'verbose_name_plural': '吃喝玩乐',
                'db_table': 't_ygeat',
            },
        ),
    ]
