# Generated by Django 2.0.1 on 2019-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ygeatmodel',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
