# Generated by Django 2.0.1 on 2019-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funy', '0004_auto_20190909_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='分类图片'),
        ),
    ]
