# Generated by Django 2.0.1 on 2019-09-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Funy', '0001_initial'),
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImageModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=200, verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 't_goods_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfoModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityinfo', models.CharField(max_length=200, verbose_name='商品说明')),
                ('sellprice', models.FloatField(verbose_name='折扣价')),
                ('subtitle', models.CharField(max_length=200, verbose_name='副标题')),
                ('unit', models.CharField(max_length=20, verbose_name='规格')),
                ('spec', models.CharField(max_length=30, verbose_name='单位/规格')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频')),
                ('placeoforgin', models.CharField(max_length=100, verbose_name='产地')),
            ],
            options={
                'verbose_name': '商品详情表',
                'verbose_name_plural': '商品详情表',
                'db_table': 't_goods_info',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityname', models.CharField(max_length=100, verbose_name='商品名')),
                ('commoditycode', models.CharField(max_length=30, verbose_name='编号')),
                ('maxlimitcount', models.IntegerField(verbose_name='最大购买数')),
                ('originalprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('goodshot', models.IntegerField(verbose_name='热度')),
                ('categoryid', models.ManyToManyField(db_table='t_goods_cate', related_name='goods_cate', to='Funy.CategoryModel', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 't_goods',
            },
        ),
        migrations.CreateModel(
            name='SiwapModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_img', models.CharField(max_length=200, verbose_name='活动大图')),
                ('active_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='Address.ActivesModel', verbose_name='活动表')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
                'db_table': 't_siwap',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 't_tag',
            },
        ),
        migrations.AddField(
            model_name='goodsinfomodel',
            name='goods_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='Goods.GoodsModel', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='goodsinfomodel',
            name='promotiontag',
            field=models.ManyToManyField(db_table='tag_goods_info', related_name='goods_tag', to='Goods.TagModel', verbose_name='标签名'),
        ),
        migrations.AddField(
            model_name='goodsimagemodel',
            name='goods_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='Goods.GoodsModel', verbose_name='商品id'),
        ),
    ]
