# Generated by Django 2.0.1 on 2019-09-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funy', '0005_auto_20190909_2042'),
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfomodel',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频'),
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='categoryid',
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='categoryid',
            field=models.ManyToManyField(db_table='t_goods_category', related_name='cate_goods', to='Funy.CategoryModel', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='commoditycode',
            field=models.CharField(max_length=30, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='commodityname',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
    ]
