# Generated by Django 2.0.1 on 2019-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_auto_20190910_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='categoryid',
            field=models.ManyToManyField(db_table='t_goods_cate', related_name='goods_cate', to='Funy.CategoryModel', verbose_name='所属分类'),
        ),
    ]
