# Generated by Django 2.0.1 on 2019-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_auto_20190910_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsinfomodel',
            name='commdityspec',
        ),
        migrations.RemoveField(
            model_name='goodsinfomodel',
            name='commoditunit',
        ),
        migrations.AddField(
            model_name='goodsinfomodel',
            name='spec',
            field=models.CharField(default=1, max_length=30, verbose_name='规格'),
            preserve_default=False,
        ),
    ]
