# Generated by Django 2.0.1 on 2019-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0005_auto_20190910_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfomodel',
            name='unit',
            field=models.CharField(default=1, max_length=20, verbose_name='规格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsinfomodel',
            name='spec',
            field=models.CharField(max_length=30, verbose_name='单位/规格'),
        ),
    ]
