# Generated by Django 2.0.1 on 2019-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0006_auto_20190910_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfomodel',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='副标题'),
        ),
    ]
