# Generated by Django 2.0.1 on 2019-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0007_auto_20190910_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfomodel',
            name='promotiontag',
            field=models.ManyToManyField(db_table='tag_goods_info', related_name='goods_tag', to='Goods.TagModel', verbose_name='标签名'),
        ),
    ]
