# Generated by Django 2.0.1 on 2019-09-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0008_goodsinfomodel_promotiontag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimagemodel',
            name='goods_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='Goods.GoodsModel', verbose_name='商品id'),
        ),
    ]
