# Generated by Django 2.0.1 on 2019-09-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0009_auto_20190911_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfomodel',
            name='goods_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='Goods.GoodsModel', verbose_name='商品id'),
        ),
    ]
