# Generated by Django 2.0.1 on 2019-09-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='UserApp.UserModel', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='UserApp.UserModel', verbose_name='用户'),
        ),
    ]
