# Generated by Django 2.0.1 on 2019-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0002_auto_20190909_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesmodel',
            name='active_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='活动跳转链接'),
        ),
    ]
