# Generated by Django 2.0.1 on 2019-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0003_auto_20190910_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesmodel',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='活动缩略图'),
        ),
    ]
