# Generated by Django 2.0.1 on 2019-09-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_usermodel_address_id'),
        ('Address', '0004_auto_20190910_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='UserApp.UserModel', verbose_name='用户'),
        ),
    ]
