# Generated by Django 2.0.1 on 2019-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0005_auto_20190911_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='state',
            field=models.BooleanField(default=True, verbose_name='是否默认'),
        ),
    ]
