# Generated by Django 2.0.1 on 2019-09-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        ('CartList', '0001_initial'),
        ('Funy', '0004_auto_20190909_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=500, verbose_name='评论内容')),
                ('comment_time', models.CharField(max_length=30, verbose_name='评论时间')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_comment', to='CartList.Order_listModel', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 't_comments',
            },
        ),
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('image', models.CharField(max_length=200, verbose_name='导航图片')),
                ('nav_child_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='Funy.CategoryModel', verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '导航表',
                'verbose_name_plural': '导航表',
                'db_table': 't_nav',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='手机号')),
                ('image', models.CharField(max_length=200, verbose_name='用户头像')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('bool', models.BooleanField(default=True, verbose_name='状态')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_address', to='Address.AddressModel')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_user',
            },
        ),
    ]
