# Generated by Django 2.0.1 on 2019-09-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20190910_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address_id',
        ),
    ]
