# Generated by Django 2.0.1 on 2019-09-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CartList', '0001_initial'),
        ('Goods', '0001_initial'),
        ('Address', '0002_auto_20190911_2124'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='UserApp.UserModel', verbose_name='用户订单ID'),
        ),
        migrations.AddField(
            model_name='order_listmodel',
            name='addr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addrs', to='Address.AddressModel', verbose_name='订单地址'),
        ),
        migrations.AddField(
            model_name='order_listmodel',
            name='goods_id',
            field=models.ManyToManyField(db_table='t_goods_order_list', related_name='goods', to='Goods.GoodsModel', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='order_listmodel',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='CartList.OrderModel', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='UserApp.UserModel', verbose_name='用户ID'),
        ),
    ]
