# Generated by Django 2.0.1 on 2019-09-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
        ('CartList', '0002_auto_20190911_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Goods.GoodsModel', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单商品详情表',
                'verbose_name_plural': '订单商品详情表',
                'db_table': 't_ordergoods',
            },
        ),
        migrations.RemoveField(
            model_name='order_listmodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='order_listmodel',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='CartList.Order_listModel', verbose_name='所属订单'),
        ),
    ]
