# Generated by Django 2.0.1 on 2019-09-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0003_auto_20190910_1937'),
        ('CartList', '0002_cartmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_listmodel',
            name='addr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='收货地址', to='Address.AddressModel', verbose_name='订单地址'),
            preserve_default=False,
        ),
    ]
