# Generated by Django 2.0.1 on 2019-09-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartList', '0003_order_listmodel_addr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='UserApp.UserModel', verbose_name='用户订单ID'),
        ),
    ]
