# Generated by Django 2.0.1 on 2019-09-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
        ('UserApp', '0002_auto_20190912_0859'),
        ('CartList', '0003_auto_20190915_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order_listmodel',
            name='order_id',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='Goods.GoodsModel', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='UserApp.UserModel', verbose_name='用户ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_listmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='UserApp.UserModel', verbose_name='所属用户'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
