# Generated by Django 2.0.1 on 2019-09-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartList', '0004_auto_20190911_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': '购物车表', 'verbose_name_plural': '购物车表'},
        ),
        migrations.AlterModelOptions(
            name='order_listmodel',
            options={'verbose_name': '订单详情表', 'verbose_name_plural': '订单详情表'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': '订单表', 'verbose_name_plural': '订单表'},
        ),
        migrations.AlterModelTable(
            name='cartmodel',
            table='t_cart',
        ),
        migrations.AlterModelTable(
            name='order_listmodel',
            table='t_odrer_list',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='t_order',
        ),
    ]
