# Generated by Django 2.0.1 on 2019-09-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CartList', '0004_auto_20190915_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='UserApp.UserModel', verbose_name='用户ID'),
        ),
    ]
