# Generated by Django 2.0.1 on 2019-09-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartList', '0005_auto_20190911_1403'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_listmodel',
            table=None,
        ),
    ]
