# Generated by Django 2.0.1 on 2019-09-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartList', '0005_auto_20190915_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='count',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
